name: Latest Post Notification

on:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  check_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          cd src
          pip install -r requirements.txt
      - name: Get latest post
        run: |
          if [ ! -f src/latest_post.txt ]; then
            touch src/latest_post.txt
          fi
          LATEST_POST="$(curl -s https://bunnieabc.com/index.xml | grep -oP '(?<=<title>)[^<]+')"
          PREVIOUS_POST="$(cat src/latest_post.txt)"
          if [ "$LATEST_POST" != "$PREVIOUS_POST" ]; then
            echo "$LATEST_POST" > src/latest_post.txt
            echo "Latest post has been updated. Sending notification to Slack..."
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"I am Lisa. The latest post is now: $LATEST_POST\"}" "${{ secrets.SLACK_WEBHOOK_URL }}"
          else
            echo "No new posts."
          fi
