name: My Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello from GitHub Actions"}' "${{ secrets.SLACK_WEBHOOK_URL }}"
