name: Verify Slack webhook URL

on: [push]

jobs:
  verify_slack_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Slack webhook URL
        run: echo "SLACK_WEBHOOK_URL secret is set to '${{ secrets.SLACK_WEBHOOK_URL }}'"
